### ISSUE TITLE
adjust size of images on about tab 

### ISSUE THREAD

**Issue by markheckmann** [markheckmann/gridsampler#33]
Images are too wide. Should be like in former versions with the GTK images.

**Comment by jemus42** [comment]
Adjusted in b203a9f1934273bb2c526aedf4a5dd6e4b8eae98

**Comment by markheckmann** [comment]
index.html in vignette folder still is unchanged. Do we still need this file?

**Comment by jemus42** [comment]
`vignettes` folder gets build by roxygen AFAIK, but the "important" one is the one in `inst/doc`, where `devtools::build_vignette()` puts it.  

To be best of my knowledge `vignettes` only needs to contain the `Rmd` and assets (like the screenshots).

EDIT:
Apparently past-me was already sure of that, since `.gitignore` has the following:

```
vignettes/*.R
vignettes/*.html
```

**Comment by jemus42** [comment]
As an aside, I have this small script in my part which I use to automatically place the built vignette in the shiny and docs folder, while also trimming style info from the shiny version so it doesn't ruin the layout in the app:

```
#! /bin/bash
# copy_vignettes.sh
# This is a helper to copy the vignette to additional locations
# i.e. 1) The shiny app's "About"-Tab 2) The docs dir for GH-pages

# Copy to shiny dir and remove stylesheets (remove lines 16-60 w/ sed)
sed '16,60d' inst/doc/index.html > inst/shiny/text/index.html;

# Copy to docs dir to update GitHub pages
cp inst/doc/index.html docs/index.html
```

I'm hesitant to commit it to the repo, but I wanted to note it somewhere.
