### ISSUE TITLE
Software fails when changing # of attributes of categories

### ISSUE THREAD

**Issue by markheckmann** [markheckmann/gridsampler#39]
When changing the number of min or max attributes of # of categories, we get a deadlock and the graphics turn grey.
![image](https://cloud.githubusercontent.com/assets/152927/20566815/b9ee18e6-b196-11e6-8416-408b6549922e.png)

**Comment by jemus42** [comment]
Can't reproduce, everything works on my end.

https://dump.jemu.name/2016-11-vdwjkwe1v9wuggn.mp4

**Comment by markheckmann** [comment]
Hhm. STrange. I restarted R and now it also works fine on my side. Sorry for the false alarm.

**Comment by jemus42** [comment]
Good, false alarm are the best alarms!

**Comment by jemus42** [comment]
I noticed how that happens:

If you run the app from RStudio and it opens in its own preview windows, and **then** you click the button to open it in the browser, the app is technically opened with 1 backend and two current states of the GUI, which in turn has the effect that the reactive value objects in the server logic get confused because they get two different states from two different open GUIs.

At least that's the way I understand it. As far as I can tell, I can't really fix that.
